### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by egoist** [shreshthmohan/rehype-color-chips#6]
Hello, the es build have external dependencies:

<img width="974" alt="CleanShot 2023-03-27 at 23 57 37@2x" src="https://user-images.githubusercontent.com/8784712/227996776-69a14c68-1a7b-4c4f-90be-0ee5fc925d01.png">

but they are only in `devDependencies` in package.json 😢

**Comment by shreshthmohan** [comment]
Thank you for pointing this out @egoist 👍🏽

Will fix it in #7 

Please review if you can

**Comment by shreshthmohan** [comment]
Version `0.1.1` has a fix.

**Comment by shreshthmohan** [comment]
@egoist  I have never been sure about using `peerDependencies` vs `dependencies`, please make a suggestion if you have any.

**Comment by egoist** [comment]
I think it's good to use dependencies here 🙆
